name: download-tauri-app-from-run-id

on:
  push:
    branches:
      - main # let it able to dispatch when push on dev
    paths:
      - ".github/workflows/download-tauri-app-from-run-id.yml"
permissions: write-all

env:
  APP_NAME: yowa
  TAURI_VERSION: v1

jobs:
  download:
    runs-on: ubuntu-20.04
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: tauri-app # save to path
          pattern: tauri-app* # down load artifacts match pattern name
          merge-multiple: false #  extracted into individual named directories within the specified path
          run-id: 9732031975
          github-token: ${{ secrets.GITHUB_TOKEN }} # for different repo or workflow
          repository: ymc-github/yowa
      - run: ls -R tauri-app
      - name: cook tauri bucket
        uses: ymc-github/yors-ghac-burn-tauri-bucket@v0.1.0
        with:
          path: tauri-app
          bucket-loc: "bucket/{name}.json"
          pkg-org: yors
          browser-download-url-prefix: "https://github.com/YMC-GitHub/yowa/releases/download/v{version}"
      - name: list tauri bucket
        shell: bash
        run: |
          ls -R bucket
        

